-- Merit Store — Supabase (Postgres) schema.
-- Run once in Supabase Dashboard → SQL Editor → New query → paste → Run.
-- Safe to re-run: everything is IF NOT EXISTS / ON CONFLICT DO NOTHING.
--
-- Security model: the browser NEVER talks to these tables. All access goes
-- through Netlify server functions using the service-role key, which bypasses
-- RLS. RLS is enabled with no policies, so the public anon key can read/write
-- nothing even if someone extracts it from the site.

-- ── Users allow-list + roles ────────────────────────────────────────────────
create table if not exists public.ms_users (
  email      text primary key check (email = lower(email)),
  role       text not null check (role in ('admin', 'encoder')),
  active     boolean not null default true,
  created_at timestamptz not null default now()
);

-- ── Privileges ──────────────────────────────────────────────────────────────
create table if not exists public.ms_privileges (
  id         text primary key,
  name       text not null,
  cost       numeric not null default 0 check (cost >= 0),
  type       text not null check (type in ('REGULAR', 'ACCOUNTABILITY')),
  active     boolean not null default true,
  unit_label text,
  quota_limit  numeric check (quota_limit is null or quota_limit >= 0),
  quota_period text    check (quota_period is null or quota_period in ('month', 'semester')),
  entry_max    numeric check (entry_max is null or entry_max > 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.ms_settings (
  key   text primary key,
  value text not null
);

-- ── Cadets ──────────────────────────────────────────────────────────────────
create sequence if not exists public.ms_cadet_seq;

create table if not exists public.ms_cadets (
  id               text primary key
                   default ('C-' || lpad(nextval('public.ms_cadet_seq')::text, 5, '0')),
  name             text not null,
  batch            text,
  available_merits numeric not null default 100 check (available_merits >= 0),
  updated_at       timestamptz not null default now()
);
create index if not exists ms_cadets_name_idx  on public.ms_cadets (lower(name));
create index if not exists ms_cadets_batch_idx on public.ms_cadets (batch);

-- ── Transactions ────────────────────────────────────────────────────────────
-- IDs (MS-000001, …) are generated by the database, so two operators encoding
-- at the same moment can never get the same ID or overwrite each other.
create sequence if not exists public.ms_txn_seq;

create table if not exists public.ms_transactions (
  id                text primary key
                    default ('MS-' || lpad(nextval('public.ms_txn_seq')::text, 6, '0')),
  cadet_id          text,
  cadet_name        text not null,
  batch             text,
  privilege_id      text,
  privilege_name    text,
  privilege_type    text not null default 'REGULAR'
                    check (privilege_type in ('REGULAR', 'ACCOUNTABILITY')),
  merit_cost        numeric not null default 0,
  availment_date    date,
  confirmation_date date,
  status            text not null default 'Pending'
                    check (status in ('Pending', 'Confirmed', 'Cancelled', 'Not Confirmed', 'Invalid')),
  merits_deducted   numeric not null default 0,
  violation         boolean not null default false,
  processed_by      text,
  remarks           text,
  quantity          numeric,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists ms_transactions_status_idx    on public.ms_transactions (status);
create index if not exists ms_transactions_availment_idx on public.ms_transactions (availment_date);
create index if not exists ms_transactions_cadet_idx     on public.ms_transactions (lower(cadet_name));
create index if not exists ms_transactions_created_idx   on public.ms_transactions (created_at desc);

-- ── Atomic balance change ───────────────────────────────────────────────────
-- Used for deducting / restoring merits so two operators can never overwrite
-- each other's balance. Balance never goes below 0 (same rule as before).
create or replace function public.ms_adjust_merits(p_cadet_id text, p_delta numeric)
returns numeric
language sql
as $$
  update public.ms_cadets
     set available_merits = greatest(0, available_merits + p_delta),
         updated_at = now()
   where id = p_cadet_id
  returning available_merits;
$$;

-- ── Lock everything down ────────────────────────────────────────────────────
alter table public.ms_users        enable row level security;
alter table public.ms_settings     enable row level security;
alter table public.ms_privileges   enable row level security;
alter table public.ms_cadets       enable row level security;
alter table public.ms_transactions enable row level security;

revoke all on public.ms_users, public.ms_settings, public.ms_privileges, public.ms_cadets, public.ms_transactions
  from anon, authenticated;
revoke all on sequence public.ms_cadet_seq, public.ms_txn_seq from anon, authenticated;
revoke execute on function public.ms_adjust_merits(text, numeric) from public, anon, authenticated;
grant  execute on function public.ms_adjust_merits(text, numeric) to service_role;

-- ── Default privileges ──────────────────────────────────────────────────────
insert into public.ms_privileges (id, name, cost, type, unit_label, quota_limit, quota_period, entry_max) values
  ('phone',               'Phone',               10, 'REGULAR',        null,                 null, null,       null),
  ('food-delivery',       'Food Delivery',       10, 'REGULAR',        null,                 null, null,       null),
  ('group-food-delivery', 'Group Food Delivery', 15, 'REGULAR',        null,                 null, null,       null),
  ('liberty',             'Liberty',             25, 'REGULAR',        null,                 null, null,       null),
  ('reduce-ed',           'Reduce ED',            2, 'ACCOUNTABILITY', 'ED Hours to Reduce', 20,   'month',    null),
  ('offset-demerits',     'Offset Demerits',      2, 'ACCOUNTABILITY', 'Demerits to Offset', 30,   'semester', 15)
on conflict (id) do nothing;

-- ── FIRST ADMIN ─────────────────────────────────────────────────────────────
-- Replace with YOUR email (lowercase), then run. After the first admin signs in
-- they can add everyone else from the Admin page → Users & Roles.
insert into public.ms_users (email, role)
values ('REPLACE_WITH_YOUR_EMAIL@example.com', 'admin')
on conflict (email) do nothing;
